# Generated by Django 6.0.6 on 2026-06-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='is_login_attempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='login_success',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
