# Generated by Django 6.0.6 on 2026-06-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_requestlog_is_login_attempt_requestlog_login_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='is_brute_force_suspect',
            field=models.BooleanField(default=False),
        ),
    ]
