# Generated by Django 6.0.6 on 2026-06-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_requestlog_is_brute_force_suspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='is_sqli_suspect',
            field=models.BooleanField(default=False),
        ),
    ]
