# Generated by Django 6.0.6 on 2026-06-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_requestlog_is_sqli_suspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='is_recon_suspect',
            field=models.BooleanField(default=False),
        ),
    ]
