# Generated by Django 6.0.6 on 2026-06-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_requestlog_is_recon_suspect'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('brute_force_count', models.IntegerField(default=0)),
                ('sqli_count', models.IntegerField(default=0)),
                ('recon_count', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-risk_score'],
            },
        ),
    ]
