# Generated by Django 6.0.6 on 2026-06-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_ipriskprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipriskprofile',
            name='llm_explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
