# Generated by Django 4.2.28 on 2026-08-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0007_ipriskprofile_llm_explanation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictiveAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_ip", models.GenericIPAddressField()),
                ("predicted_stage", models.CharField(max_length=200)),
                ("predicted_asset", models.CharField(max_length=200)),
                ("confidence", models.CharField(default="MEDIUM", max_length=50)),
                ("reasoning", models.TextField()),
                ("recommended_action", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ThreatHuntFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hunt_type",
                    models.CharField(
                        choices=[
                            ("LOW_AND_SLOW", "Low-and-Slow Stealth Attack"),
                            ("DISTRIBUTED_PROBING", "Coordinated Multi-IP Probing"),
                            ("ANOMALOUS_BURST", "Anomalous Request Frequency Burst"),
                            ("CREDENTIAL_STUFFING", "Distributed Credential Stuffing"),
                            ("ZERO_DAY_ANOMALY", "High-Deviation Zero-Day Anomaly"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_entity", models.CharField(max_length=150)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("evidence_data", models.TextField(blank=True, default="{}")),
                (
                    "mitigation_action",
                    models.CharField(
                        default="Monitor and evaluate entity", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active Finding"),
                            ("MITIGATED", "Mitigated / IP Quarantined"),
                            ("RESOLVED", "Resolved / Cleared"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="ipriskprofile",
            name="anomaly_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ipriskprofile",
            name="fused_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ipriskprofile",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ipriskprofile",
            name="llm_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ipriskprofile",
            name="ml_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ipriskprofile",
            name="path_traversal_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ipriskprofile",
            name="predicted_next_stage",
            field=models.CharField(
                blank=True, default="Unknown — Monitoring", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="ipriskprofile",
            name="predicted_target_asset",
            field=models.CharField(blank=True, default="/login/", max_length=200),
        ),
        migrations.AddField(
            model_name="ipriskprofile",
            name="prediction_confidence",
            field=models.CharField(blank=True, default="LOW", max_length=50),
        ),
        migrations.AddField(
            model_name="ipriskprofile",
            name="rule_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ipriskprofile",
            name="sequence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ipriskprofile",
            name="xss_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="requestlog",
            name="entropy_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="requestlog",
            name="inferred_intent",
            field=models.CharField(default="Legitimate Traffic", max_length=100),
        ),
        migrations.AddField(
            model_name="requestlog",
            name="is_path_traversal_suspect",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="requestlog",
            name="is_xss_suspect",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="requestlog",
            name="query_params",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="requestlog",
            name="request_rate",
            field=models.FloatField(default=0.0),
        ),
    ]
